# Generated by Django 3.1.13 on 2022-02-16 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220214_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.datetime(2022, 2, 16, 9, 22, 15, 914366, tzinfo=utc))),
                ('text', models.TextField()),
                ('approved_comment', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='customer.customer')),
            ],
        ),
    ]
