# Generated by Django 3.1.13 on 2022-02-16 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220217_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='customer',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
